### PR TITLE
Global Page: Initializing the sidebar and table

### PR DESCRIPTION
**Pull request by ronyyosef**
Resume of this #69 PR

### CODE REVIEW

**Comment by ronyyosef** [comment]
@adiabramovitch 
I have tested it and it is working well
Ready for merge

**Review by ShellyGolden — APPROVED** [review]

**Comment by adiabramovitch** [comment]
Looks good overall, but what about tests?
For example, we should add tests about which msg is shown when there aren't instances in the DB or what happens when the number of houses is too big,  do we have a limit for this table? maybe we should add a scroller?

**Comment by ronyyosef** [comment]
> Looks good overall, but what about tests? For example, we should add tests about which msg is shown when there aren't instances in the DB or what happens when the number of houses is too big, do we have a limit for this table? maybe we should add a scroller?

There is a logic to display message if there are not instances to show, its made with django templates feature . It's looks something like this {empty} in the forblock

About too big table, there is a limit for anything, html files can be very big. I thing for the MVP we don't  need to do scale tests

**Comment by adiabramovitch** [comment]
> > Looks good overall, but what about tests? For example, we should add tests about which msg is shown when there aren't instances in the DB or what happens when the number of houses is too big, do we have a limit for this table? maybe we should add a scroller?
> 
> There is a logic to display message if there are not instances to show, its made with django templates feature . It's looks something like this {empty} in the forblock
> 
> About too big table, there is a limit for anything, html files can be very big. I thing for the MVP we don't need to do scale tests

It is not a scale test. I think adding a scroller or limiting the size of the table is a must.
otherwise, if you have 30 house records how is it going to be shown?

**Review by LiorKGOW — APPROVED** [review]
Could you please add a screenshot of the updated Global Page?

**Comment by ronyyosef** [comment]
> > > Looks good overall, but what about tests? For example, we should add tests about which msg is shown when there aren't instances in the DB or what happens when the number of houses is too big, do we have a limit for this table? maybe we should add a scroller?
> > 
> > 
> > There is a logic to display message if there are not instances to show, its made with django templates feature . It's looks something like this {empty} in the forblock
> > About too big table, there is a limit for anything, html files can be very big. I thing for the MVP we don't need to do scale tests
> 

https://user-images.githubusercontent.com/61323123/163789253-c63ef7d0-b8d5-46d3-9907-ad5ea29e78e2.mov


> It is not a scale test. I think adding a scroller or limiting the size of the table is a must. otherwise, if you have 30 house records how is it going to be shown?

There is a scroller, Here is a video that displays how it is looking, I have tested it with 500 items and it looks good

**Comment by ronyyosef** [comment]
@adiabramovitch Ready for merge

**Pull request merged**
