### PR TITLE
Adding vagrantfile and modify .gitignore to include .vagrant

### PR DESCRIPTION
**Pull request by ronyyosef**
Creating a Vagrantfile for a working Vagrant environment with file sharing. 
add .vagrant to git ignore.

fix https://github.com/redhat-beyond/Xpense/issues/1

### CODE REVIEW

**Comment by bregman-arie** [comment]
Spelling mistake in commit: "and modife"
Also, adding some details to the commit message about the content of the Vagrant file (or why you ignore .vagrant), might be helpful for reviewers to review your change.

**Comment by yuvalk** [comment]
when your commit msg include the word "and" it means your commit is not atomic. (ie - doing mulitple things) and in most cases (like this) it is better to split the commit

**Comment by yuvalk** [comment]
> Spelling mistake in commit: "and modife" Also, adding some details to the commit message about the content of the Vagrant file (or why you ignore .vagrant), might be helpful for reviewers to review your change.
+1
in general the commit msg should explain the why (the what can be observed from the diff..)

**Comment by LiorKGOW** [comment]
@ronyyosef I took a look on the PR, nice work rony 👍

**Review by LiorKGOW — APPROVED** [review]

**Comment by adiabramovitch** [comment]
@ronyyosef Nice work Rony. 
Please pay attention to Yuval's comment, it is recommended to split the PR when you use the word "and" in order to describe the commit.

**Comment by ronyyosef** [comment]
Opening two PRs

**Comment by adiabramovitch** [comment]
Sorry, I deleted my comment because I miss read Yuval's comment. He meant two commits and not two PRs. 
If you already did the change, leave it.

**Comment by ronyyosef** [comment]
Hey @adiabramovitch , I already closed this PR.
That was really funny to do a pr with one line of git ignore

**Comment by yuvalk** [comment]
for future reference, you dont need to close the PR, just update it.

**Pull request closed without merging**
