### PR TITLE
House: Filter only public houses to show on global page

### PR DESCRIPTION
**Pull request by shlior7**

### CODE REVIEW

**Review by LiorKGOW — APPROVED** [review]
Good Call @shlior7 👍

**Review by Yoavsc129 — APPROVED** [review]

**Review by ronyyosef — APPROVED** [review]

**Comment by adiabramovitch** [comment]
a test checking that is missing. 
I want to see that private houses do not appear on the global page.

**Comment by LiorKGOW** [comment]
I think this could be merged
three team members approved so i added the label 👍

**Comment by adiabramovitch** [comment]
please rebase

**Review by ShellyGolden — APPROVED** [review]

**Review by ronyyosef — APPROVED** [review]

**Review by svatares — APPROVED** [review]

**Pull request merged**
