### PR TITLE
Init house app

### PR DESCRIPTION
**Pull request by LiorKGOW**
adding the house app to the INSTALLED_APPS

Depends on PR #21

### CODE REVIEW

**Comment by LiorKGOW** [comment]
#21 merged, pushed again after main rebase

**Review by ronyyosef — APPROVED** [review]
Looks great!

**Review by Yoavsc129 — APPROVED** [review]

**Review by shlior7 — APPROVED** [review]
LGTM

**Comment by adiabramovitch** [comment]
Although they will be empty files, for now, shouldn't you add:
house/tests.py 
house/views.py 
house/__init__.py as well? 
I am asking because I saw that on a different PR you decided to add them, it is good practice to be consistent.

**Comment by svatares** [comment]
@LiorKGOW I agree with @adiabramovitch , test files should e added along with the app files. First thing is to keep on consistency, second thing is that it will be easier to add tests when adding new code and no new files will need to be introduced in future PRs.

**Comment by LiorKGOW** [comment]
> Although they will be empty files, for now, shouldn't you add: house/tests.py house/views.py house/**init**.py as well? I am asking because I saw that on a different PR you decided to add them, it is good practice to be consistent.

@adiabramovitch You are right, I will add them
Thanks 👍

**Comment by svatares** [comment]
@LiorKGOW please fix failing tests/checks

**Comment by LiorKGOW** [comment]
> @LiorKGOW please fix failing tests/checks

fixed 👍

**Comment by svatares** [comment]
@LiorKGOW noticed it only after I merged, but next time please squash the commits, since the second commit doesn't really make any difference, it is basically part of the initialization.

**Comment by LiorKGOW** [comment]
> @LiorKGOW noticed it only after I merged, but next time please squash the commits, since the second commit doesn't really make any difference, it is basically part of the initialization.

Ok thanks
I'll keep it in mind 👌

**Pull request merged**
