### PR TITLE
Xpense: Updating ERD with Tips

### PR DESCRIPTION
**Pull request by LiorKGOW**
Updating ERD to the latest version including the Tips app

### CODE REVIEW

**Review by ShellyGolden — COMMENTED** [review]
I think that the tips app needs to connect to the house. 
Like the story app.

**Comment by LiorKGOW** [comment]
> I think that the tips app needs to connect to the house. 
> 
> Like the story app.

Correct me if I'm wrong,
I thought the Tips app is just random tips that would be displayed at the Web page of the user, therefore it is not connected directly to House.
Unlike Tips, the Story is *written by the user* so it needs to be connected directly to House

**Review by Yoavsc129 — APPROVED** [review]

**Review by ShellyGolden — APPROVED** [review]

**Comment by ShellyGolden** [comment]
> > I think that the tips app needs to connect to the house.
> > Like the story app.
> 
> Correct me if I'm wrong, I thought the Tips app is just random tips that would be displayed at the Web page of the user, therefore it is not connected directly to House. Unlike Tips, the Story is _written by the user_ so it needs to be connected directly to House

Ok :)
got it
I approved the PR

**Comment by adiabramovitch** [comment]
image

I think it is duplicated.

**Comment by LiorKGOW** [comment]
> image
> 
> I think it is duplicated.

fixed

**Comment by adiabramovitch** [comment]
About Tips, do you mean that each tip is associated with a specific category?
I mean, it is not related to statistics or something just "Good to know tips" regarding the category?

**Comment by LiorKGOW** [comment]
> About Tips, do you mean that each tip is associated with a specific category? I mean, it is not related to statistics or something just "Good to know tips" regarding the category?

It could be both

**Comment by adiabramovitch** [comment]
OK, but basing tips on statistics does not appear in your current implementation, so I want to make sure that "Good to know tips" regarding the category is the implementation for now.

**Comment by LiorKGOW** [comment]
> OK, but basing tips on statistics does not appear in your current implementation, so I want to make sure that "Good to know tips" regarding the category is the implementation for now.

Yes, at least for now

**Review by orIsrael — APPROVED** [review]

**Pull request merged**
