### PR TITLE
Init expenses app

### PR DESCRIPTION
**Pull request by ronyyosef**
init expenses app
adding the app to the INSTALLED_APPS
#29

### CODE REVIEW

**Review by ShellyGolden — APPROVED** [review]

**Comment by svatares** [comment]
@ronyyosef you have some conflicts to resolve here

**Comment by ronyyosef** [comment]
@svatares after some learning about how to do git rebase correct it's now ready

**Review by shlior7 — APPROVED** [review]
Looks Good
this is the perfect example of initializing a new app

**Comment by ronyyosef** [comment]
Hey, @yuvalk 
Can you take a look at this?

**Pull request merged**
