### PR TITLE
House: Login Page Basic Routing

### PR DESCRIPTION
**Pull request by LiorKGOW**
Dependent on #58 

#58 was merged 👍

### CODE REVIEW

**Comment by ronyyosef** [comment]
Waiting to see that coming

**Comment by LiorKGOW** [comment]
> Waiting to see that coming

In the oven

**Comment by svatares** [comment]
@LiorKGOW blocking PR merged, please rebase

**Comment by adiabramovitch** [comment]
@LiorKGOW plz rebase

**Comment by LiorKGOW** [comment]
> Dependent on #58

#58 was merged 👍

**Comment by LiorKGOW** [comment]
rebased and repushed after #67 was merged

**Comment by adiabramovitch** [comment]
> rebased and repushed after #67 was merged

You still have three commit

**Pull request closed without merging**
