### PR TITLE
vagrant setup fix: wasnt migrating initially

### PR DESCRIPTION
**Pull request by shlior7**
added setup command to automate the migration with the setup as instructed  
image

### CODE REVIEW

**Comment by ronyyosef** [comment]
Looks great!

**Comment by LiorKGOW** [comment]
good job! @shlior7

**Review by LiorKGOW — APPROVED** [review]

**Review by Yoavsc129 — APPROVED** [review]

**Comment by adiabramovitch** [comment]
Two commits are not necessary, can you squash the commits? 
Can you please describe commit messages as requested here: https://cbea.ms/git-commit/?

**Comment by orIsrael** [comment]
Nice work!

**Comment by adiabramovitch** [comment]
You should capitalize your commit message and follow those conventions. 
https://cbea.ms/git-commit/

**Review by LiorKGOW — APPROVED** [review]

**Pull request merged**
