### PR TITLE
Formatting: format code and create pre-commit that format code automatically 

### PR DESCRIPTION
**Pull request by shlior7**
example and guide was taken mainly from [here](https://rednafi.github.io/digressions/python/2020/04/06/python-precommit.html#:~:text=Running%20the%20Linters%20as%20Pre%2Dcommit%20Hooks,-To%20run%20the&text=settings%20to%20the%20.-,pre%2Dcommit%2Dconfig.,the%20line%20at%2079%20characters.)

more about pre-commit and its hooks [here](https://pre-commit.com/hooks.html)

more about black formatter [here](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html)

### CODE REVIEW

**Comment by adiabramovitch** [comment]
Can you please add this formatter as a github action?

**Comment by shlior7** [comment]
> Can you please add this formatter as a github action?

https://github.com/marketplace/actions/gradual-black-formatter
seems too complicated to be honest

**Comment by adiabramovitch** [comment]
> > Can you please add this formatter as a github action?
> 
> https://github.com/marketplace/actions/gradual-black-formatter seems too complicated to be honest
> 
> I can do a pre-commit framework like so : https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/ wyt?

Doesn't look complicated at all it is the same YAML file as flake 8 but with the black formatter, they are giving you the action to be added

I want the format to be added as a test for each PR like the flake 8

**Comment by shlior7** [comment]
Added a pre-commit action that :
1. remove trailling white spaces
2. fix eof white space
3. makes sure all string are single quotes
4. run black and flake8
:) 
@adiabramovitch @ronyyosef @ShellyGolden @LiorKGOW @orIsrael @Yoavsc129

**Comment by shlior7** [comment]
> > > Can you please add this formatter as a github action?
> > 
> > 
> > https://github.com/marketplace/actions/gradual-black-formatter seems too complicated to be honest
> > I can do a pre-commit framework like so : https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/ wyt?
> 
> Doesn't look complicated at all it is the same YAML file as flake 8 but with the black formatter, they are giving you the action to be added
> 
> I want the format to be added as a test for each PR like the flake 8 you can do it any way you preffer

Instead of a test for everyone that have maybe a different formatter or IDE the pre-commit will magicly format and set a format style for everyone on commit.

**Comment by adiabramovitch** [comment]
Can you change the second commit message to start with a capital letter and add a Format title 
like:
`Format: Add pre-commit using flake8 and black`

**Pull request merged**
