### PR TITLE
Xpense: Adding DFD

### PR DESCRIPTION
**Pull request by LiorKGOW**
Graphical representation of the flow
of data through our system, modeling its process aspects

Link to the Diagram in Gliffy: https://go.gliffy.com/go/html5/13629865

### CODE REVIEW

**Review by ShellyGolden — APPROVED** [review]

**Review by ronyyosef — APPROVED** [review]

**Comment by adiabramovitch** [comment]
@shlior7  @Yoavsc129 @orIsrael  can you approve as well?

**Review by Yoavsc129 — APPROVED** [review]

**Review by shlior7 — APPROVED** [review]

**Review by shlior7 — COMMENTED** [review]
description = story ?

**Comment by LiorKGOW** [comment]
> description = story ?

Waiting on the disduccsion in Slack, then I'll fix it in the file

**Comment by ronyyosef** [comment]
It need to be repush to rerun the tests

**Review by ShellyGolden — APPROVED** [review]

**Comment by adiabramovitch** [comment]
I don't entirely understand what each shape represents, what are the circles stand for? a button? a web page? an endpoint? 
What do you mean by post tips? a user can add tips on his own? 
which statistics are you looking for? what do filter parameters mean? 
The DFD is supposed to be very clear and does not require any explanations

**Comment by LiorKGOW** [comment]
> I don't entirely understand what each shape represents, what are the circles stand for? a button? a web page? an endpoint? What do you mean by post tips? a user can add tips on his own? which statistics are you looking for? what do filter parameters mean? The DFD is supposed to be very clear and does not require any explanations

The circles represent processes, The squares are multiple entities that are not inside the program (like here the users) and the third shape is a Data Base we read it here: https://www.lucidchart.com/pages/data-flow-diagram .
Plus on the gliffy site when you edit the diagram, the shapes have names (Data Base)
for instance, creation of a new house requires for the user to give his expenses, story, city and country (etc.)
that processes accesses the DB, implements a new house, and returns the user 
The filter parameters are the parameters the user has to give the system in order for the filtering to show something
you filter by a spesific parameter (category, city, country, number of children etc..)

**Comment by LiorKGOW** [comment]
rebased and repushed

**Review by ShellyGolden — APPROVED** [review]

**Review by Yoavsc129 — APPROVED** [review]

**Review by ronyyosef — APPROVED** [review]

**Review by svatares — CHANGES_REQUESTED** [review]
Although the new diagram you've created looks better and makes some of the flow clearer, I do think it will be better creating it with the standard components in the industry.
You can look for those here https://en.wikipedia.org/wiki/Data-flow_diagram or https://www.lucidchart.com/pages/data-flow-diagram for example.

Also, seems to me that there are some flows missing such as: when a user browse for tips, where is that data coming from and which action requests it?
How can a user define his account? Where does the data is coming as an input and where it is stored?
How can a user change the status of his account from private to public?
In public view, where is the data is coming from, which action requests it?

You should keep in mind that all the functionalities you want to have in the app should be described in DFD somehow. Even things that is taken for granted such as data being shown on a public or private page, should be coming from some sort of data base, hence it requires a request for that data to be shown.
When editing data, personal or expense, you first request the data you want to edit from the relevant DB and then show it in the page, if user saves the new data a save/post request is being sent with the new data to the DB but if the user cancels the operation it should not save anything and take them back to the private page.

I hope it is elaborate enough to make it clearer.
Everyone in the team should think on the relevant data flow for his part/app Lior should do everything by him-selft

**Comment by LiorKGOW** [comment]
rebased and repushed after #56 merge

**Comment by ShellyGolden** [comment]
About the tips page - we need to add the option to view tips
About the private page - 1. we need to add the option to add the house information
                                         2. we need to add the option to edit the house information
I don't have an option to login to gliffy (my trial time has expired) :(

**Comment by svatares** [comment]
Was there any change done in the diagram? I still see the same one I commented on

**Comment by LiorKGOW** [comment]
> Was there any change done in the diagram? I still see the same one I commented on

Yes, We have updated the new DFD now

**Review by ronyyosef — APPROVED** [review]
Looks great 👌

**Comment by shlior7** [comment]
I think we should also add as @svatares suggested the functionality of changing data of the house like private <-> public, name change, add expenses  etc
also the filtered_houses should also be pointed out that these are the public_filtered_houses
other than that it looks amazing and very detailed Good Job @LiorKGOW and everyone who worked on this 👏

**Review by ShellyGolden — APPROVED** [review]

**Comment by LiorKGOW** [comment]
Rebased after #63 was merged,
and added suggested changes 👍

**Review by Yoavsc129 — APPROVED** [review]
Looks good!

**Review by ronyyosef — APPROVED** [review]

**Review by svatares — APPROVED** [review]

**Review by svatares — COMMENTED** [review]
This diagram looks much better! Great work!
I do have a few questions, once those will be answered we will be able to continue:

1. From the flow of the I see that anyone (even without a user) can create a tips, is that the intended behavior? Since you don't go through an authentication/login stage before reaching the "add a tip" view.
2. Anyone can view the global houses page and filter as they want. Is that right? (again no need for login to do it according to the diagram)
3. Is it possible to edit an expense? It is not mentioned in the diagram, and the flow of editing is different than the flow of adding.
4. Is it possible to edit tips? If so, same as the previous question, but also, since adding a tip (according to the current diagram) is done without authentication, how to you plan to get the information for getting the tip that you want to edit? (you want only the user that created the tip to be able to edit it)
5. I would recommend also adding the link to the Gliffyv diagram, since it is really hard to see something in here.

**Comment by LiorKGOW** [comment]
> This diagram looks much better! Great work! I do have a few questions, once those will be answered we will be able to continue:
> 
> 1. From the flow of the I see that anyone (even without a user) can create a tips, is that the intended behavior? Since you don't go through an authentication/login stage before reaching the "add a tip" view.
> 2. Anyone can view the global houses page and filter as they want. Is that right? (again no need for login to do it according to the diagram)
> 3. Is it possible to edit an expense? It is not mentioned in the diagram, and the flow of editing is different than the flow of adding.
> 4. Is it possible to edit tips? If so, same as the previous question, but also, since adding a tip (according to the current diagram) is done without authentication, how to you plan to get the information for getting the tip that you want to edit? (you want only the user that created the tip to be able to edit it)
> 5. I would recommend also adding the link to the Gliffyv diagram, since it is really hard to see something in here.

I'll add a link to the gliffy 👍 
For The rest of the questions I'll move the conversation to Slack because I think everyone should express their opinions on the subject

**Comment by LiorKGOW** [comment]
rebased and repushed after #58 was merged to main

**Comment by LiorKGOW** [comment]
> This diagram looks much better! Great work! I do have a few questions, once those will be answered we will be able to continue:
> 
> 1. From the flow of the I see that anyone (even without a user) can create a tips, is that the intended behavior? Since you don't go through an authentication/login stage before reaching the "add a tip" view.
> 2. Anyone can view the global houses page and filter as they want. Is that right? (again no need for login to do it according to the diagram)
> 3. Is it possible to edit an expense? It is not mentioned in the diagram, and the flow of editing is different than the flow of adding.
> 4. Is it possible to edit tips? If so, same as the previous question, but also, since adding a tip (according to the current diagram) is done without authentication, how to you plan to get the information for getting the tip that you want to edit? (you want only the user that created the tip to be able to edit it)
> 5. I would recommend also adding the link to the Gliffyv diagram, since it is really hard to see something in here.

resolved 👍

**Comment by LiorKGOW** [comment]
rebased and repushed after #67 was merged

**Comment by LiorKGOW** [comment]
Updated the DFD with the final version after todays meeting.
Ready to merge 👍

**Review by ShellyGolden — APPROVED** [review]

**Comment by svatares** [comment]
Good job, looks much better

**Pull request merged**
