### PR TITLE
General: linting and organizing

### PR DESCRIPTION
**Pull request by shlior7**
some linting using the 'black' formatter and checked with flake8

### CODE REVIEW

**Comment by ronyyosef** [comment]
Is that important? most of the team don't work with that formater so you will need to format others code all the time.
I think that before we use it, we need to talk about it as a team, and what are the advantages of using that.
Then if we want we will all use that linter and work according to its standard

**Comment by ShellyGolden** [comment]
I would like to get explanation about that PR

**Comment by shlior7** [comment]
In general there was unnecessary spacing and lines
category = category [here](https://github.com/redhat-beyond/Xpense/pull/64/files#diff-f675790e4216f6092649f8e48b651573457a5a04b3ace4b2cfb33461200bf25fL33)
also other than that it doesn't really matter but I do suggest synchronizing a formatter between us 
It gives a warning when flake8 is not happy which saves me time pushing lint errors and finding it on github actions

**Comment by adiabramovitch** [comment]
Didn't see that there is a discussion open and I merged it. 
But I think using a formatter is great, that way the code looks cleaner and cohesive.

**Pull request merged**
