### PR TITLE
Xpense: Updating DFD

### PR DESCRIPTION
**Pull request by LiorKGOW**
- Adding Sign Up Process
- Making things a little nicer

Addressing Issue #131

### CODE REVIEW

**Review by shlior7 — CHANGES_REQUESTED** [review]
Great work!
The sign up page doesn't go directly to create house so i think just remove that line and its good to go

**Review by Yoavsc129 — APPROVED** [review]

**Comment by ronyyosef** [comment]
> Great work! The sign up page doesn't go directly to create house so i think just remove that line and its good to go

Just fix this one and it will be approve

**Comment by LiorKGOW** [comment]
> Great work! The sign up page doesn't go directly to create house so i think just remove that line and its good to go

Fixed 👍

**Review by shlior7 — APPROVED** [review]

**Review by ShellyGolden — APPROVED** [review]

**Comment by adiabramovitch** [comment]
Do we have a welcome page? I am almose sure we removed it.

**Comment by LiorKGOW** [comment]
Successfully rebased and repushed after #128 & #132 merge to main 👍

**Comment by LiorKGOW** [comment]
> Do we have a welcome page? I am almost sure we removed it.

We do have a home page, it contains just the title, but there is one

Home Page

**Pull request merged**
