### PR TITLE
Expenses:  add category choice filed to the expenses model with init options

### PR DESCRIPTION
**Pull request by ronyyosef**
Add Expenses model and the category field

Here is how its looks in the admin panel:
image
image
image
✌✌✌
#30

### CODE REVIEW

**Review by Yoavsc129 — COMMENTED** [review]
This commit also appers in your previous PR

**Comment by ronyyosef** [comment]
> The commit 'Init expenses app' also appers in your previous PR
Yes, That's because I started from the previous branch, with all of his commits, after #22  will be approved I will be able to rebase

**Review by ShellyGolden — APPROVED** [review]

**Comment by ronyyosef** [comment]
Can you take a look at this? @yuvalk

**Comment by svatares** [comment]
@ronyyosef PR #22 was approved and merged, please rebase

**Comment by svatares** [comment]
@ronyyosef please rename the PR according to the new standard, so it will be clear what happens in the commit and to which app it belongs

**Pull request merged**
