### PR TITLE
Added ERD

### PR DESCRIPTION
**Pull request by LiorKGOW**
This Entity Relationship Diagram shows the relationships of entity sets stored in our database.

### CODE REVIEW

**Comment by ShellyGolden** [comment]
@orIsrael Please take a look at your part

**Review by shlior7 — APPROVED** [review]
Looks Great!
So the only app missing in the PR stage is the Tips?

**Comment by ronyyosef** [comment]
@orIsrael The Tips app

**Comment by svatares** [comment]
@orIsrael @LiorKGOW @ronyyosef @shlior7 Are we going to wait for the tips app to be updated, or is it going to happen in the future and you'd like to merge it now and push update in the future?

**Comment by svatares** [comment]
@orIsrael @LiorKGOW @ronyyosef @shlior7 Are we going to wait for the tips app to be updated, or is it going to happen in the future and you'd like to merge it now and push update in the future?

**Comment by LiorKGOW** [comment]
> @orIsrael @LiorKGOW @ronyyosef @shlior7 Are we going to wait for the tips app to be updated, or is it going to happen in the future and you'd like to merge it now and push update in the future?

For now I think we'll merge it and we'll update it in the future.
the reason is that the main idea is ready, it's just and extra feature.

Do you think it is the right call? @svatares

**Comment by yuvalk** [comment]
small comment on commit msg, can it actually say ERD and not ER Diagram?
easier to search for ERD which is the usual name..

**Comment by yuvalk** [comment]
also can you all approve it?
@Yoavsc129 @shlior7 @ronyyosef @ShellyGolden @orIsrael @LiorKGOW

**Review by Yoavsc129 — APPROVED** [review]

**Comment by LiorKGOW** [comment]
Changed the name of the commit to "Added ERD" @yuvalk

**Review by shlior7 — APPROVED** [review]

**Review by orIsrael — COMMENTED** [review]
Looks great!

**Review by ShellyGolden — COMMENTED** [review]
With regard to slack - didn’t we decide on adding the option of advertising the data on the house app?
@LiorKGOW 
@shlior7

**Comment by shlior7** [comment]
> With regard to slack - didn’t we decide on adding the option of advertising the data on the house app?

you're right we did add the boolean field `public` to the house model
I also think we should add an explicit house_id other than the id generated by sql,
it would be easier to reference and to debug that way wyt? @ronyyosef @LiorKGOW @ShellyGolden @Yoavsc129 @orIsrael

**Comment by LiorKGOW** [comment]
> > With regard to slack - didn’t we decide on adding the option of advertising the data on the house app?
> 
> you're right we did add the boolean field `public` to the house model I also think we should add an explicit house_id other than the id generated by sql, it would be easier to reference and to debug that way wyt? @ronyyosef @LiorKGOW @ShellyGolden @Yoavsc129 @orIsrael

Just like I commented on #28 :)
I think it would be better this way

if everybody agrees i'll add it to the ERD as well

**Comment by LiorKGOW** [comment]
> With regard to slack - didn’t we decide on adding the option of advertising the data on the house app? @LiorKGOW @shlior7

yes we did
the best option is the boolean public like Lior said in my opinion

**Comment by LiorKGOW** [comment]
pushed the latest changes of the ERD

**Review by ronyyosef — APPROVED** [review]

**Review by ShellyGolden — APPROVED** [review]

**Pull request merged**
