### PR TITLE
General: creating the base and home html

### PR DESCRIPTION
**Pull request by shlior7**

### CODE REVIEW

**Comment by ronyyosef** [comment]
Looks awesome
Can you please add some photos next time?
Also, we need to write our code like in your templates/home.html
@orIsrael @ShellyGolden @LiorKGOW @Yoavsc129

**Comment by shlior7** [comment]
image

currently only home button

**Review by ShellyGolden — APPROVED** [review]
looks good

**Review by LiorKGOW — APPROVED** [review]

**Review by ronyyosef — APPROVED** [review]

**Review by LiorKGOW — APPROVED** [review]

**Comment by adiabramovitch** [comment]
@shlior7 you need to resolve conflicts

**Comment by shlior7** [comment]
conflicts resolved and rebases @adiabramovitch  👍

**Review by svatares — APPROVED** [review]

**Pull request merged**
