### PR TITLE
Main: remove "main" app from are project

### PR DESCRIPTION
**Pull request by ronyyosef**
The main app was created by Lior Shtaimberg for the first demo and it is not needed anymore because we are going to create new views for are project

### CODE REVIEW

**Comment by ronyyosef** [comment]
The tests do not pass because there are no tests in the project

**Comment by adiabramovitch** [comment]
Why delete the app and not use it to create the UI you want?

**Comment by ronyyosef** [comment]
> authentication

The UI will be created in the House app and in the Tips app
In the Django framework, every app is like a software component, the House and expenses is not a good example because we decided to break it into two separate apps but the Tips App is a good example
The Tips app can be built as a reusable Django app. for example another project can just add the routing and register the app in the setting file and it will reuse it.
About the authentication, we will not implement an authentication system for the third demo, maybe in the future if that's where the course will take us

Our plan in general: 
 3 apps-House, Expenses, Tips 
 2 places for the view(UI) - Tips and House
We can meet and talk about the architecture of the project If it's not clear or we want to change our plan

**Review by Yoavsc129 — APPROVED** [review]

**Review by LiorKGOW — APPROVED** [review]
Good call @ronyyosef

**Pull request merged**
